services:
  web:
    build: ./frontend
    expose: 
      - 80
    networks:
      - frontend
  api:
    build: ./backend
    expose:
      - 8000
    networks:
      - frontend
      - backend
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    networks:
      - frontend
    volumes:
      - ./data/dev/nginx:/etc/nginx/conf.d

networks:
  frontend:
  backend: