services:
  web:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    depends_on:
      - api
    expose: 
      - 80
    networks:
      - frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
  api:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - frontend
      - backend
    environment:
      - BASE_URL=${BASE_URL}
    secrets:
      - DB_PASSWORD
  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    depends_on:
      - api
      - web
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - frontend
    volumes:
      - ./data/prod/Caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - BASE_URL=${BASE_URL}
  db:
    image: mysql:9.2
    restart: unless-stopped
    networks:
      - backend
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_ONETIME_PASSWORD: yes
      MYSQL_DATABASE: autocross
      MYSQL_USER: autocross
      MYSQL_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
      - ./data/sql:/docker-entrypoint-initdb.d
    secrets:
      - DB_PASSWORD

networks:
  frontend:
  backend:

secrets:
  DB_PASSWORD:
    environment: "DB_PASSWORD"

volumes:
  db_data:
  caddy_data:
  caddy_config: